services:
  #codex-frontend:
  
  fastapi_backend:
    build:
      context: ./
    env_file:
      - .env
    #secrets:  # How to import secrets to the app in the container
    #  - database_url
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: ./requirements.txt
        - action: sync
          path: ./app
          target: ./
        - action: sync
          path: ./app/func
          target: ./func
        - action: sync
          path: ./app/routers
          target: ./routers
        - action: sync
          path: ./app/static
          target: ./static
    networks:
      - codex-network

networks:
  codex-network:
    name: medical-codex-net
    # comment if creating new network
    external: true

volumes:
  codex-database:
  wikidata_names:

  # Add Sensitive information to secrets files to then be loaded
  #secrets:
  #  database_url: # Loads secret from external file
  #    external: true
  