services:
  fastapi_backend:
    build:
      context: ./
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - codex-network
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: ./Dockerfile
networks:
  codex-network:
    name: medical-codex-net
